### ISSUE TITLE
Header Line Height

### ISSUE THREAD

**Issue by benjaminmodayil** [vigetlabs/GroundRules#35]
Text gets too close.

![screen shot 2017-07-27 at 11 48 24 am](https://user-images.githubusercontent.com/12306850/28679550-880bfb76-72c1-11e7-920a-4b610fc6de2e.png)

**Comment by benjaminmodayil** [comment]
Min-height needs to be adjusted.
![screen shot 2017-07-27 at 11 50 55 am](https://user-images.githubusercontent.com/12306850/28679667-f3834094-72c1-11e7-8bc0-144dcf619cb4.png)
![screen shot 2017-07-27 at 11 51 10 am](https://user-images.githubusercontent.com/12306850/28679668-f3872f10-72c1-11e7-8236-8bf59e1af300.png)

**Comment by ccomp** [comment]
I will address this in my `roasts` build!
