### ISSUE TITLE
[QA] Animations for Device Problems Do Not Start

### ISSUE THREAD

**Issue by jroodman** [vigetlabs/GroundRules#44]
Browser: Chrome
URL: groundrules.co/devices

_Current:_
*On the Device Page, when a problem is selected and the problem content appears, the SVG image appears but the animation does not start 

_Expected:_
*On the Device Page, when a problem is selected and the problem content appears, animations (SVGs) present in the content should start and repeat

**Comment by benjaminmodayil** [comment]
They start. Closing.
