### ISSUE TITLE
[QA] Arrow for Device Problems Should be Gray (uncolored) Until Selected

### ISSUE THREAD

**Issue by jroodman** [vigetlabs/GroundRules#58]
Browser: Chrome
URL: GroundRules.co/devices

_Current:_
*Arrows for Device Problems are Coral colored in every state

_Expected:_
*Arrows for Device Problems are gray when unselected, and Coral when the Device Problem content has been opened

**Comment by benjaminmodayil** [comment]
Done. Closing.
