### ISSUE TITLE
[QA] No Hover-State Should Exist on Device Problem Arrows

### ISSUE THREAD

**Issue by jroodman** [vigetlabs/GroundRules#61]
Browser: Chrome
Url: GroundRules.co/devices

_Current:_
*A red box appears around a Device Problem's arrow when hovered over by a mouse
*A light blue box appears around a Device Problem's arrow when selected

_Expected:_
*No red box (no hover state)
*No blue box(no selected state)

**Comment by benjaminmodayil** [comment]
Not sure where you're seeing blue. Submitting a screenshot would've been helpful here. I've removed the hover state but kept the "focused" state outline there. It's needed for accessibility.

**Comment by jroodman** [comment]
Reopening this. Better! Added Screenshot. The red-box outline should not be there and is not in the comps. 

![screen shot 2017-08-04 at 10 19 41 am](https://user-images.githubusercontent.com/29235514/28972685-969e15a0-78fe-11e7-8d39-d6d4796718fb.png)

**Comment by benjaminmodayil** [comment]
Done. 😏
