### ISSUE TITLE
[QA] mobile: white space after footer

### ISSUE THREAD

**Issue by csjennin** [vigetlabs/GroundRules#72]
https://groundrules.co/roasts and https://groundrules.co/devices
mobile Safari

current:
-when you scroll all the way down the page, there is white space after the footer

expected:
-footer should align with bottom of the page
-there should be no white space after the footer

**Comment by benjaminmodayil** [comment]
Not seeing this anymore. I was fixing something else related and must have fixed this one by accident. Closing.
